logging:
  level:
    ROOT: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: another canned concierge blinked debate email sculpture
    url: jdbc:postgresql://localhost:5432/lennys_bakery
    username: loki
  jpa:
    hibernate:
      ddl-auto: create