logging:
  level:
    ROOT: DEBUG
spring:
  profile: dev
  datasource:
    url: jdbc:sqlite:./db/db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always