CREATE SEQUENCE IF NOT EXISTS account_profile_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE account_profile
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    avatar_filename VARCHAR(255),
    about           VARCHAR(255),
    users_id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_accountprofile PRIMARY KEY (id)
);

ALTER TABLE account_profile
    ADD CONSTRAINT uc_accountprofile_users UNIQUE (users_id);

ALTER TABLE account_profile
    ADD CONSTRAINT FK_ACCOUNTPROFILE_ON_USERS FOREIGN KEY (users_id) REFERENCES users (id);