CREATE SEQUENCE IF NOT EXISTS public.tags_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE tags
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    slug        VARCHAR(255)                             NOT NULL,
    description VARCHAR(1000)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    tags_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);