CREATE SEQUENCE IF NOT EXISTS public.inventory_item_images_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE inventory_item_images
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_filename        VARCHAR(255)                             NOT NULL,
    inventory_item_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    inventory_item_images INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_inventory_item_images PRIMARY KEY (id)
);