CREATE TABLE inventory_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(200)                            NOT NULL,
    short_description VARCHAR(200)                            NOT NULL,
    description       VARCHAR(1000)                           NOT NULL,
    price             DECIMAL                                 NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_item PRIMARY KEY (id)
);