CREATE SEQUENCE IF NOT EXISTS public.users_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE users
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(25)                              NOT NULL,
    password        VARCHAR(100)                             NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    avatar_filename VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);