CREATE SEQUENCE IF NOT EXISTS public.cart_items_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE cart_items
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    inventory_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    quantity          INTEGER                                   NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);